---
- hosts: cs_nodes
  become: yes
  become_user: root
  roles:
    - node
  vars_files:
    - vars_files/database_conf.yml

- hosts: cs_databases
  become: yes
  become_user: root
  roles:
    - database
  vars_files:
    - vars_files/database_conf.yml
