---
- name: install packages
  apt:
    name: "{{ items }}"
    state: present
  vars:
    items:
      - postgresql
      - postgresql-contrib

- name: debconf xroad-common
  debconf:
    name: xroad-common
    question: "xroad-common/username"
    vtype: "string"
    value: "{{ xroad_ui_user }}"

- name: debconf xroad-proxy
  debconf:
    name: xroad-proxy
    question: "{{ item.question }}"
    vtype: "string" # parametrize if you add a different type of question to item list
    value: "{{ item.value }}"
  with_items:
    - { question: "xroad-common/service-altsubject", value: "IP:{{ ansible_default_ipv4['address'] }},DNS:{{ inventory_hostname }}" }
    - { question: "xroad-common/admin-altsubject",   value: "IP:{{ ansible_default_ipv4['address'] }},DNS:{{ inventory_hostname }}" }
    - { question: "xroad-common/service-subject",    value: "/CN={{ inventory_hostname }}" }
    - { question: "xroad-common/admin-subject",      value: "/CN={{ inventory_hostname }}" }
    - { question: "xroad-common/username",           value: "{{ xroad_ui_user }}" }
    
- name: install xroad security server packages
  apt:
    name: "{{ vars['xroad_varpkg_' + variant] }}"
    state: latest
    force: yes
