---
- name: Copy RPM packages (RHEL)
  become: yes
  copy: src={{item}} dest=/xroad/local/RPMS/ force=no
  with_fileglob:
    - ../src/packages/build/rhel/{{ ansible_distribution_major_version }}/noarch/xroad-*rpm
    - ../src/packages/build/rhel/{{ ansible_distribution_major_version }}/x86_64/xroad-*rpm

- name: Clear yum cache (RHEL)
  become: yes
  command: yum clean all
  args:
    warn: no
